onlineshop/Models/CheckoutViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace onlineshop.Models
{
    public class CheckoutViewModel
    {
        [Required]
        public required string Name { get; set; }

        [Required]
        public required string City { get; set; }

        [Required]
        public required string Address { get; set; }

    }
}

onlineshop/Controllers/OnlineShopController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using onlineshop.Helper;
using onlineshop.Models;
using onlineshop.Repositroy;
using System.Security.Claims;


namespace onlineshop.Controllers
{
    public class OnlineShopController : Controller
    {
        private readonly IOnlineShop _onlineShop;
        private readonly IProduct _product;
        private readonly IMapper _mapper;
        private readonly IHttpClientFactory _clientFactory;

        public OnlineShopController(IOnlineShop onlineShop, IProduct product, IMapper mapper, IHttpClientFactory clientFactory)
        {
            _onlineShop = onlineShop;
            _product = product;
            _mapper = mapper;
            _clientFactory = clientFactory;
        }
        [HttpPost]
        public async Task<IActionResult> AddToBasket(Guid id, int quantity)
        {
            #region user-product
            if (!User.Identity.IsAuthenticated)
            {
                return Unauthorized();
            }
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var product = await _product.GetProductById(id);
            #endregion
            #region condition
            var productConvert = product.Product;
            if (product == null || !productConvert.IsAvailable || productConvert.Quantity == 0)
            {
                return View("ProductNotFound");
            }
            else if (quantity > productConvert.Quantity)
            {
                ViewBag.name = productConvert.Name;
                return View("LimitedProduct");
            }
            #endregion
            #region TempOrder
            var tempOrder = HttpContext.Session.GetObject<T_TempOrder>("tempOrder");
            if (tempOrder == null)
            {
                var result =  _onlineShop.CreateNewOrder(user);
                tempOrder = result.Data as T_TempOrder;
                HttpContext.Session.SetObject("tempOrder", tempOrder);
            }
            #region TempBasket
            var basketList = HttpContext.Session.GetObject<List<T_TempBasket>>("tempBasket") ?? new List<T_TempBasket>();
            var existingItem = basketList.FirstOrDefault(c => c.T_Product_ID == productConvert.ID_Product);
            if (existingItem == null)
            {
                var result =  _onlineShop.AddNewTempBasket(tempOrder, productConvert, quantity);
                var newItem = result.Data as T_TempBasket;
                basketList.Add(newItem);
            }
            else
            {

                var tempList = _onlineShop.UpdateTempBasket(existingItem, existingItem.Product, quantity);
                HttpContext.Session.SetObject("tempBasket", tempList.Data);

            }
            HttpContext.Session.SetObject("tempBasket", basketList);

            #endregion
            #endregion

            return RedirectToAction("ShowBasket");
        }

        [HttpGet]
        public IActionResult ShowBasket()
        {
            #region show basket
            if (!User.Identity.IsAuthenticated)
            {
                return Unauthorized();
            }
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var tempOrderSession = HttpContext.Session.GetObject<T_TempOrder>("tempOrder");
            if (tempOrderSession == null)
            {
                return View();
            }

            var expirationTime = TimeSpan.FromMinutes(3);
            var currentTime = DateTime.Now;
            var elapsed = currentTime - tempOrderSession.CreatedAt;
            var tempBasketSession = HttpContext.Session.GetObject<List<T_TempBasket>>("tempBasket");
            if (elapsed >= expirationTime)
            {
                HttpContext.Session.Remove("tempBasket");
                HttpContext.Session.Remove("tempOrder");
                return RedirectToAction("ShowBasket");

            }
            return View(tempBasketSession);
            #endregion

        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(CheckoutViewModel model)
        {
            #region user-order-basket
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var tempOrder = HttpContext.Session.GetObject<T_TempOrder>("tempOrder");
            var tempBasket = HttpContext.Session.GetObject<List<T_TempBasket>>("tempBasket");
            var tempBasketFiltered = tempBasket.Where(c => c.T_tempOrder_ID == tempOrder.ID_TempOrder).ToList();
            #endregion
            #region checking items
            if (tempBasketFiltered == null)
            {
                return NotFound();
            }
            #endregion
            #region creating order
            var order = await _onlineShop.AddOrder(model, user);
            #endregion
            #region creating basket
            await _onlineShop.AddBasket(tempBasketFiltered, order);
            #endregion
            #region delete basket
            HttpContext.Session.Remove("tempBasket");
            HttpContext.Session.Remove("tempOrder");
            #endregion
            return RedirectToAction("Showorder"); // can goes to showorder
        }

        [HttpGet]
        public async Task<IActionResult> Showorder()
        {
            #region user-order

            if (!User.Identity.IsAuthenticated)
            {
                return Unauthorized();
            }
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var order = await _onlineShop.GetOrderByUserId(user);
            var orderConverted = order.Data as T_Order;
            if (orderConverted == null)
            {
                return View();
            }
            #endregion
            #region mapping basket
            var details = await _onlineShop.GetAllByOrder(orderConverted.ID_Order);
            var detailsConverted = details.Data as List<T_Basket>;
            var orderDetails = _mapper.Map<List<BasketViewModel>>(detailsConverted);
            #endregion
            #region calculating the totalprice
            long totalPrice = 0;
            foreach (var item in orderDetails)
            {
                if (item.Product.IsDiscountActive && item.Product.Discount.HasValue)
                {
                    totalPrice += DiscountExtention.GetDiscount(item.Product) * item.Quantity;

                }
                else
                {
                    totalPrice += item.Product.Price * item.Quantity;
                }
            }

            #endregion
            #region mapping order
            var finalOrder = new OrderViewModel
            {
                Address = orderConverted.Address,
                City = orderConverted.City,
                Name = orderConverted.Name,
                BasketDetails = orderDetails,
                OrderStatus = orderConverted.OrderStatus,

            };
            ViewBag.price = totalPrice;
            return View(finalOrder);
            #endregion
        }
        [HttpGet]
        public async Task<IActionResult> ShowAllOrders()
        {
            #region user-order

            if (!User.Identity.IsAuthenticated)
            {
                return Unauthorized();
            }
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var order = await _onlineShop.GetAllOrderByUserId(user);
            var orderConverted = order.Data as List<T_Order>;
            if (orderConverted == null)
            {
                return NotFound();
            }
            #endregion
            return View(orderConverted);
        }




        [HttpPost]
        public IActionResult DeleteItems(Guid tempBasket)
        {
            #region delete items 

            var tempBasketSession = HttpContext.Session.GetObject<List<T_TempBasket>>("tempBasket");
            if (!User.Identity.IsAuthenticated)
            {
                return Unauthorized();
            }
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (tempBasketSession == null)
            {
                return RedirectToAction("ShowBasket");
            }

            var itemToRemove = tempBasketSession.FirstOrDefault(c => c.ID_TempBasket == tempBasket);
            tempBasketSession.Remove(itemToRemove);
            HttpContext.Session.SetObject("tempBasket", tempBasketSession);

            return RedirectToAction("ShowBasket");
            #endregion
        }

        [HttpPost]
        public IActionResult EditItems(Guid tempBasket, int quantity)
        {
            #region edit item
            var tempBasketSession = HttpContext.Session.GetObject<List<T_TempBasket>>("tempBasket");
            var existingItem = tempBasketSession.FirstOrDefault(c => c.ID_TempBasket == tempBasket);
            if (existingItem == null)
            {
                return NotFound();
            }
            var tempList = _onlineShop.UpdateTempBasket(existingItem, existingItem.Product, quantity);
            HttpContext.Session.SetObject("tempBasket", tempList.Data);
            return RedirectToAction("ShowBasket");
            #endregion
        }

        [HttpGet]
        public IActionResult ProductDetail()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ProductDetail(Guid productId)
        {
            var product = await _onlineShop.ProductDetail(productId);
            if (product.IsSuccess)
            {
                return View(product.Data);
            }
            else
            {
                return NotFound(product.Message);
            }
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Payment()
        {

            #region Creating trackid

onlineshop/Views/OnlineShop/Checkout.cshtml
@model CheckoutViewModel
@{
    ViewData["Title"] = "Checkout";
}

<h1>CheckOut</h1>

<h4>AddingInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Checkout" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>



            <div class="form-group mt-2">
                <input type="submit" value="Place The Order " class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ShowBasket">Basket</a>
</div>

onlineshop/Views/OnlineShop/OnlinePayment.cshtml
@{
    ViewData["Title"] = "OnlinePayment";
}

<h1>OnlinePayment</h1>

<table class="table table-stripped table-bordered table-dark">

    <tr>

        <td>Payment Result</td>
        <td>Payment Code</td>

    </tr>

    <tr>
        <td>Successful</td>
        <td>@ViewBag.code</td>
    </tr>

</table>

onlineshop/Views/OnlineShop/ProductDetail.cshtml
@using onlineshop.Helper
@model T_Product;

<div class="container py-5">
    <h2 class="text-center mb-5">@Model.Name</h2>
    <div class="row">
        <div class="col-md-4 mb-4">
            <div class="card">
                @foreach (var photo in Model.Photos)
                {
                    <img src="/@photo.ImageUrl" class="card-img-top" alt="A sleek modern laptop with a high-resolution screen">

                }
                <div class="card-body">
                    <h5 class="card-title">@Model.Name</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">@Model.Quantity</p>
                    @if (Model.IsDiscountActive && Model.Discount.HasValue)
                    {
                        <p class="card-text"><small class="text-body-secondary" style="text-decoration:line-through">Price: @Model.Price.ToString("N0")</small></p>

                        <p class="card-text"><small class="text-body-secondary">Price with discount: @DiscountExtention.GetDiscount(Model).ToString("N0")</small></p>
                    }
                    else
                    {
                        <p class="card-text"><small class="text-body-secondary">Price: @Model.Price.ToString("N0")</small></p>

                    }
                    <form method="post" asp-action="AddToBasket" asp-controller="OnlineShop" onsubmit="disableButton(this)">
                        <input type="hidden" name="id" value="@Model.ID_Product" />
                        <div class="form-group">
                            @Html.TextBox("quantity", 1, new { @type = "number", @min = "1", @id = "quantity" })
                        </div>
                        <button type="submit" class="btn btn-sm btn-info mt-2" id="addToBasketButton">Add to Basket</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function disableButton(form) {
        const button = form.querySelector('#addToBasketButton');
        button.disabled = true;
        button.innerText = 'Adding...'; // Optional: Change button text to indicate action
    }
</script>

onlineshop/Views/OnlineShop/SearchProduct.cshtml
@using onlineshop.Helper
@model IEnumerable<T_Product>

@if (Model != null && Model.Any())
{
    <!-- Products Section -->
    <div class="container py-5">
        <h2 class="text-center mb-5">Featured Products</h2>
        <div class="row">
            <!-- Product 1 -->
            @foreach (var product in Model)
            {
                <div class="col-md-4 mb-4">
                    <div class="card">
                        @foreach (var photo in product.Photos)
                        {
                            <img src="/@photo.ImageUrl" class="card-img-top" alt="A sleek modern laptop with a high-resolution screen">

                        }
                        <div class="card-body">
                            <h5 class="card-title">@product.Name</h5>
                            <p class="card-text">In Stock: @product.Quantity</p>
                            <form asp-action="ProductDetail" asp-controller="OnlineShop" method="post" style="display:inline">
                                <input type="hidden" value="@product.ID_Product" name="productId" />
                                <button type="submit" class="btn btn-success">View Details</button>
                            </form>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
}
else
{
    <p>There is no product.</p>
}

onlineshop/Views/OnlineShop/ShowAllOrders.cshtml
@model List<T_Order>;
@{
}


<table class="table">
    <thead>
        <tr>
            <th>Product Name</th>
            <th>Image</th>
            <th>Oder Time</th>
            <th>Finalized</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var orders in Model)
        {

            foreach (var products in orders.Baskets)
            {
                <tr>
                    <td>@products.Product.Name</td>
                    @foreach (var photo in products.Product.Photos)
                    {
                        <td>
                            <img src="/@photo.ImageUrl" class="border-radius" style="max-width : 150px" />
                        </td>
                    }
                    <td>
                        @orders.OrderDate
                    </td>
                    <td>
                        @if (orders.IsFinal == false)
                        {
                            <i class="bi bi-x-circle"></i>
                        }
                        else
                        {
                            <i class="bi bi-check-circle"></i>

                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

onlineshop/Views/OnlineShop/ShowBasket.cshtml
@model IEnumerable<T_TempBasket>
@{
    ViewData["Title"] = "ShowBasket";
}


@if (Model != null && Model.Any())
{
    @foreach (var item in Model)
    {
        <div class="card">
            <div class="card-header">
                @User.Identity.Name Basket
            </div>
            <div class="card-body">
                @foreach (var photo in item.Product.Photos)
                {
                    <img class="border-radius" src="/@photo.ImageUrl" style="width:200px;height:200px">
                }
                <h3 class="card-title">@item.Product.Name</h3>
                <p class="card-text">@item.Quantity</p>
                <p class="card-text">@item.TotalPrice.ToString("N0")</p>
                <div class="d-flex align-items-end">
                    <form method="post" asp-action="EditItems" class="d-flex align-items-end">
                        <input hidden name="tempBasket" value="@item.ID_TempBasket" />
                        <div class="form-group mb-2 me-2">
                            @Html.TextBox("quantity", item.Quantity, new { @type = "number", @min = "1" })
                        </div>
                        <button type="submit" class="btn btn-danger me-2">Edit</button>

                    </form>

                    <form method="post" asp-action="DeleteItems">
                        <input hidden name="tempBasket" value="@item.ID_TempBasket" />
                        <button type="submit" class="btn btn-danger mt-2">Delete</button>
                    </form>
                </div>


            </div>
        </div>
    }
}
else
{
    <h2>There is no basket</h2>
    <hr />
}
<a class="btn alert-success" href="/OnlineShop/checkout">Add Order</a>
<a class="btn alert-info" href="/Home/Index">Continue Shopping</a>

onlineshop/Views/OnlineShop/Showorder.cshtml
@using onlineshop.Helper
@using shoppingApp.Extention
@model OrderViewModel
@{
    ViewData["Title"] = "Showorder";
}

<h2>Order Details</h2>

@if(Model != null)
{


<div>
    <h3>Customer Information</h3>
    <p><strong>Name:</strong> @Model.Name</p>
    <p><strong>Address:</strong> @Model.Address</p>
    <p><strong>City:</strong> @Model.City</p>
    <p><strong>Status:</strong> @Model.OrderStatus.GetDisplayName()</p>

</div>

<div>
    <h3>Order Items</h3>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Product Photo</th>
                    <th>Price</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var detail in Model.BasketDetails)
                {
                    <tr>
                        <td>@detail.Product.Name</td>
                        @foreach (var photo in detail.Product.Photos)
                        {
                            <td>
                                <img src="/@photo.ImageUrl" class="border-radius" style="max-width : 150px" />
                            </td>
                        }
                        <td>
                            @if (detail.Product.IsDiscountActive && detail.Product.Discount.HasValue)
                            {
                                @DiscountExtention.GetDiscount(detail.Product).ToString("N0")
                                ;
                            }
                            else
                            {
                                @detail.Product.Price.ToString("N0")
                            }

                        </td>
                        <td>@detail.Quantity</td>
                    </tr>
                }
                <tr>
                    <th>TotalPrice</th>
                    <td>@ViewBag.price.ToString("N0")</td>

            </tbody>
        </table>
    </div>

</div>

<form method="post" asp-action="Payment" asp-controller="OnlineShop" onsubmit="disableButton(this)">

    <button type="submit" class="btn btn-primary">Do the Payment now!</button>
</form>
}
else
{
    <p>No items found for this order.</p>
}